### ISSUE TITLE
Autolink ending with '/' in an image

### ISSUE THREAD

**Issue by danieldongit** [lezer-parser/markdown#39]
There is an issue with using Autolink and Images together.
If a URL is placed in the caption of an image, it highlights it as a URL (as expected).

However, if that URL ends in a '/' character it breaks the image parsing. This issue can be seen in the screenshot provided and the test environment both linked below. 

Note: I did test this in GitHub itself and the issue did not occur. 

Screenshot (first is correct second isn't):

![Image](https://github.com/lezer-parser/markdown/assets/150142406/4927fc29-756e-44ba-92b1-60308dfd449c)

Test environment:
https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge21hcmtkb3duTGFuZ3VhZ2UsIG1hcmtkb3dufSBmcm9tICJAY29kZW1pcnJvci9sYW5nLW1hcmtkb3duIgppbXBvcnQge2xhbmd1YWdlc30gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZ3VhZ2UtZGF0YSIKCi8vIFRoZSBNYXJrZG93biBwYXJzZXIgd2lsbCBkeW5hbWljYWxseSBsb2FkIHBhcnNlcnMKLy8gZm9yIGNvZGUgYmxvY2tzLCB1c2luZyBAY29kZW1pcnJvci9sYW5ndWFnZS1kYXRhIHRvCi8vIGxvb2sgdXAgdGhlIGFwcHJvcHJpYXRlIGR5bmFtaWMgaW1wb3J0LgpsZXQgdmlldyA9IG5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICJIZWxsb1xuXG5gYGBqYXZhc2NyaXB0XG5sZXQgeCA9ICd5J1xuYGBgIiwKICBleHRlbnNpb25zOiBbCiAgICBiYXNpY1NldHVwLAogICAgbWFya2Rvd24oe2NvZGVMYW5ndWFnZXM6IGxhbmd1YWdlcywgYmFzZTogbWFya2Rvd25MYW5ndWFnZX0pCiAgXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK

**Comment by marijnh** [comment]
What is happening is that the [autolink](https://github.github.com/gfm/#autolinks-extension-) extension is consuming the closing `]` as part of the URL. I see nothing in that spec that would cause the bracket to not be part of the URL token: "After a [valid domain](https://github.github.com/gfm/#valid-domain), zero or more non-space non-< characters may follow". Then there's some special handling for parentheses and semicolons, but no mention of brackets.

But it seems like GitHub's implementation differs from the spec. A lone URL _will_ include the bracket, but when it is embedded in a link or image text, it won't.

This seems to go agains how CommonMark does tokenization, which isn't dependent on surrounding markers. But since this is GFM, not CommonMark, we don't have a rigorous spec available, and I guess someone added a kludge to their parser to address this specific case.

Attached patch does the same in our parser.
