### ISSUE TITLE
Custom MediaConfig to style Markdown table in monospace font.

### ISSUE THREAD

**Issue by TechMaster** [lezer-parser/markdown#46]
**My motivation**
In CodeMirror 6 editor that edit Markdown document, I want to format table in **monospace font**, so I can format table like this:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/20d1873e-5b2b-42fe-a104-3304fbedb469">

```md
| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Text     | Text     | Text     |
| Text     | Text     | Text     |
| Text     | Text     | Text     |
```

**My Code**
I write a custom MediaConfig as follow
```js
const TableDelim = { resolve: 'Table' };
export const Table = {
  defineNodes: ['Table', 'TableRow', 'TableCell'],
  parseInline: [
    {
      name: 'Table',
      parse(cx, next, pos) {
        if (next !== 124 /* '|' */ || cx.char(pos + 1) !== 124) {
          return -1;
        }
        return cx.addDelimiter(TableDelim, pos, pos + 1, true, true);
      }
    },
  ],
  props: [
    styleTags({
      'Table/...': defaultTags.monospace,
      'TableRow/...': defaultTags.monospace,
      'TableCell/...': defaultTags.monospace,
      'TableRow:first-child': defaultTags.strong,
    }),
  ],
} as MarkdownConfig;
```
**The result**
<img width="774" alt="image" src="https://github.com/user-attachments/assets/037a5a4d-7c68-42df-ba2c-916ff293cc87">

**I debug and found that**
The second line is skipped in my above code. I really don't know what is really going inside lezer/markdown. 

**Please help**
1. How can I make the second line formatted in monospace like other lines in markdown table?
2. Markdown table should be parsed in my custom Media Config not in default code to speed up rendering performance.

Please help. Many thanks.

**Comment by marijnh** [comment]
Do I understand correctly that you aren't using the [table extension](https://github.com/lezer-parser/markdown?tab=readme-ov-file#user-content-table) from @lezer/markdown, but your own inline parser that recognizes the pipe characters? The one from this package actually parses tables as a single node spanning the entire table, and should not have the problem you describe. You can add style tags to nodes defined by other extensions.

**Comment by TechMaster** [comment]
My own inline parser checks if a line contains character '|' at begin and end then it concludes this line is a row of a markdown table or not.

> The one from this package actually parses tables as a single node spanning the entire table, and should not have the problem you describe. You can add style tags to nodes defined by other extensions.

Please give me some more hint or code example how to **style tags to node.**

Many thanks

**Comment by marijnh** [comment]
[This example](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge21hcmtkb3dufSBmcm9tICJAY29kZW1pcnJvci9sYW5nLW1hcmtkb3duIgppbXBvcnQge1RhYmxlfSBmcm9tICJAbGV6ZXIvbWFya2Rvd24iCmltcG9ydCB7c3R5bGVUYWdzLCB0YWdzfSBmcm9tICJAbGV6ZXIvaGlnaGxpZ2h0IgoKbmV3IEVkaXRvclZpZXcoewogIGRvYzogYE5vdCBhIHRhYmxlCiAgCnwgVGhpcyB8IElzIHwKfCAtLS0gIHwgLS0tIHwKfCBBICAgIHwgVGFibGUgfGAsCiAgZXh0ZW5zaW9uczogW2Jhc2ljU2V0dXAsIG1hcmtkb3duKHtleHRlbnNpb25zOiBbCiAgICBUYWJsZSwKICAgIHsKICAgICAgcHJvcHM6IFsKICAgICAgICBzdHlsZVRhZ3MoewogICAgICAgICAgJ1RhYmxlLy4uLic6IHRhZ3MuYXRvbSwKICAgICAgICB9KQogICAgICBdCiAgICB9LAogIF19KV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==) loads the built-in Table extension and adds the atom tag to all table contents (because monospace wouldn't be visible in the output).
